// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8lXfB1uKav1meU3wB4lOlodC-ShKDTD0',
    appId: '1:1083531581119:web:d05b5e8122f967b1c5980a',
    messagingSenderId: '1083531581119',
    projectId: 'login-e41d5',
    authDomain: 'login-e41d5.firebaseapp.com',
    storageBucket: 'login-e41d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL6XFKoIJRoZNXyD-1VR0oWujskIcCips',
    appId: '1:1083531581119:android:645919c20f1962e8c5980a',
    messagingSenderId: '1083531581119',
    projectId: 'login-e41d5',
    storageBucket: 'login-e41d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd3xlGJY__GdJim9SAg3ZPj9pFJcyThGM',
    appId: '1:1083531581119:ios:6164267b26858db9c5980a',
    messagingSenderId: '1083531581119',
    projectId: 'login-e41d5',
    storageBucket: 'login-e41d5.appspot.com',
    androidClientId: '1083531581119-q12unfcvv3nf8a1n11ceh9g1kvhvusra.apps.googleusercontent.com',
    iosClientId: '1083531581119-8bgqmghsagaflq0rm83v87vq6rd9vq2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd3xlGJY__GdJim9SAg3ZPj9pFJcyThGM',
    appId: '1:1083531581119:ios:6164267b26858db9c5980a',
    messagingSenderId: '1083531581119',
    projectId: 'login-e41d5',
    storageBucket: 'login-e41d5.appspot.com',
    androidClientId: '1083531581119-q12unfcvv3nf8a1n11ceh9g1kvhvusra.apps.googleusercontent.com',
    iosClientId: '1083531581119-8bgqmghsagaflq0rm83v87vq6rd9vq2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );
}
